name: Deploy

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: build api
        run: dotnet build dnd-api/DnD.API.csproj

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: build ui
        working-directory: dnd-ui
        run: |
          npm ci
          npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: dnd-api-unittests
    steps:
      - uses: actions/checkout@v4

      - name: run unit tests
        run: dotnet test

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: configure testsettings
        run: |
          echo '{"selfhosted": true, "url": ""}' > testsettings.json

      - name: run integration tests
        run: dotnet test dnd-api-integrationtests/DnD.API.IntegrationTests.csproj
