name: Deploy

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: build api
        run: dotnet build dnd-api/DnD.API.csproj

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: build ui
        working-directory: dnd-ui
        run: |
          npm ci
          npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: dnd-api-unittests
    steps:
      - uses: actions/checkout@v4

      - name: run unit tests
        run: dotnet test

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: configure testsettings
        run: |
          echo '{"selfhosted": true, "url": ""}' > testsettings.json

      - name: run integration tests
        run: dotnet test dnd-api-integrationtests/DnD.API.IntegrationTests.csproj

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  ui-tests:
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: dnd-ui-tests
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: install browsers
        run: npx playwright install --with-deps firefox

      - name: run ui tests
        run: npx playwright test --project=firefox
        env:
          BASE_URL: ${{ vars.VERCEL_URL }}
          DND_USERNAME: ${{ secrets.DND_USERNAME }}
          DND_PASSWORD: ${{ secrets.DND_PASSWORD }}
